name: Run tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:

env:
  PACKAGE_VERSION: "1.0.${{ github.run_id }}"
  USER: ${{ github.actor }}
  TOKEN: ${{ secrets.TOKEN_TEST }}
  NAMESPACE: 'cpintado'
  GHES_HOSTNAME: 'cpintado-37.westeurope.cloudapp.azure.com'
  SUBDOMAIN_ISOLATION: 'false'
  REPOSITORY_URL: 'https://cpintado-37.westeurope.cloudapp.azure.com/${{ github.repository }}'

jobs:

  build:
    name: Build the image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$PACKAGE_VERSION

  test-publish-nuget:
    runs-on: ubuntu-latest
    needs: build
    name: Publish a Nuget package to a test server
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$PACKAGE_VERSION
    - name: Publish a Nuget package
      run: |
        docker run -e USER -e TOKEN -e NAMESPACE -e GHES_HOSTNAME\
        -e SUBDOMAIN_ISOLATION -e PACKAGE_VERSION\
        -e REPOSITORY_URL\
        ghcr.io/${{ github.repository }}:$PACKAGE_VERSION
