name: Run tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:

env:
  VERSION: "1.0.${{ github.run_id }}"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$VERSION
