name: Run tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  workflow_dispatch:

env:
  PACKAGE_VERSION: "1.0.${{ github.run_id }}"
  USER: ${{ github.actor }}
  TOKEN: ${{ secrets.TOKEN_TEST }}
  NAMESPACE: 'cpintado'
  GHES_HOSTNAME: 'cpintado-37.westeurope.cloudapp.azure.com'
  SUBDOMAIN_ISOLATION: 'false'
  REPOSITORY_URL: 'https://cpintado-37.westeurope.cloudapp.azure.com/${{ github.repository }}'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.repository }}:$PACKAGE_VERSION
